"""Flow IR → Temporal workflow emitter (Tier 2).

Walks the comprehensive :class:`~offramp.extract.flow.ir.FlowIR` control-flow
graph and emits a *structurally faithful* Temporal workflow — not a single
``perform_step`` placeholder. The emitted module mirrors the Flow's actual
shape:

* each side-effecting element (DML, action call, lookup) → one ``@activity.defn``
  stub, named after the element, called from the workflow in execution order;
* decisions → ``if/elif/else`` over the rules' real conditions;
* loops → a Python ``for`` over the collection, body emitted inline;
* fault connectors → ``try/except`` with the error path emitted;
* subflows → ``workflow.execute_child_workflow`` against the child Flow.

The traversal emits each element once (a shared ``visited`` set); join points
and back-edges become ``pass  # → <name>`` markers so the generated code is
always valid Python and terminates. Activities are stubs to implement against
the MCP gateway — per the project convention, the translator emits a reviewed
skeleton, not production logic. But the skeleton now encodes the real branching,
looping, and data flow, which is the whole point.
"""

from __future__ import annotations

import re

from offramp.core.models import Component
from offramp.extract.flow.ir import (
    ConnectorKind,
    FlowDecisionRule,
    FlowElement,
    FlowElementType,
    FlowIR,
)
from offramp.generate.tier2 import GeneratedWorkflow

# Element types that become a Temporal activity (a durable side effect / I/O).
_ACTIVITY_TYPES = {
    FlowElementType.RECORD_CREATE,
    FlowElementType.RECORD_UPDATE,
    FlowElementType.RECORD_DELETE,
    FlowElementType.RECORD_LOOKUP,
    FlowElementType.ACTION_CALL,
    FlowElementType.APEX_PLUGIN_CALL,
}

# Salesforce condition operator → Python comparison.
_OP_TO_PY = {
    "EqualTo": "==",
    "NotEqualTo": "!=",
    "GreaterThan": ">",
    "GreaterThanOrEqualTo": ">=",
    "LessThan": "<",
    "LessThanOrEqualTo": "<=",
}
_CONDITION_LOGIC = {"and": " and ", "or": " or "}

_HEADER = '''\
"""Auto-generated Temporal workflow (from Flow IR).

Generated by offramp.generate.flow_emitter. Do not edit by hand — regenerate.
Activities are stubs: implement each against the MCP gateway. Human review
required before deployment.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import activity, workflow
'''


def _safe_id(s: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"f_{cleaned}"
    return cleaned


def emit_flow_workflow(component: Component, ir: FlowIR) -> GeneratedWorkflow:
    """Emit a Temporal workflow module from a Flow's IR."""
    return _Emitter(component, ir).emit()


class _Emitter:
    def __init__(self, component: Component, ir: FlowIR) -> None:
        self.component = component
        self.ir = ir
        self.cls = f"Flow_{_safe_id(component.api_name or component.name)}"
        self.resource_names = {r.name for r in ir.resources}
        self.visited: set[str] = set()
        self.body: list[str] = []
        # activity name → (element_type, detail) for stub generation, ordered.
        self.activities: dict[str, tuple[str, str]] = {}

    # -- public ------------------------------------------------------------

    def emit(self) -> GeneratedWorkflow:
        entry = self._entry_target()
        self._walk(entry, indent=2)
        # Scheduled paths are alternate entry points — note them for the human.
        scheduled = self.ir.start.scheduled_paths if self.ir.start else []
        sched_notes = [
            f"        # scheduled path {sp.name!r} → {sp.connector.target!r} "
            f"(offset {sp.offset_number} {sp.offset_unit}); wire via Temporal Schedule"
            for sp in scheduled
            if sp.connector
        ]

        code = self._assemble(sched_notes)
        return GeneratedWorkflow(
            workflow_id=f"flow.{self.component.name}",
            workflow_name=self.cls,
            activity_names=tuple(self.activities),
            code=code,
        )

    # -- traversal ---------------------------------------------------------

    def _walk(self, name: str | None, indent: int) -> None:
        pad = "    " * indent
        if not name:
            self.body.append(f"{pad}return self.ctx")
            return
        if name in self.visited:
            self.body.append(f"{pad}pass  # → {name} (handled above)")
            return
        self.visited.add(name)
        el = self.ir.element_by_name(name)
        if el is None:
            self.body.append(f"{pad}pass  # unresolved element {name!r}")
            return

        et = el.element_type
        if et is FlowElementType.DECISION:
            self._emit_decision(el, indent)
        elif et is FlowElementType.LOOP:
            self._emit_loop(el, indent)
        elif et is FlowElementType.ASSIGNMENT:
            self._emit_assignment(el, indent)
        elif et is FlowElementType.SUBFLOW:
            self._emit_subflow(el, indent)
        elif et in _ACTIVITY_TYPES:
            self._emit_activity_element(el, indent)
        elif et in {FlowElementType.SCREEN, FlowElementType.WAIT}:
            self._emit_pause(el, indent)
        else:
            self.body.append(f"{pad}# {et.value} {el.name!r} — passthrough")
            self._walk(self._next(el), indent)

    def _emit_activity_element(self, el: FlowElement, indent: int) -> None:
        pad = "    " * indent
        act = self._register_activity(el)
        call = [
            f"{pad}self.ctx[{el.name!r}] = await workflow.execute_activity(",
            f"{pad}    {act},",
            f"{pad}    args=[record, self.ctx],",
            f"{pad}    start_to_close_timeout=timedelta(seconds=30),",
            f"{pad})",
        ]
        fault = self._connector_target(el, ConnectorKind.FAULT)
        if fault:
            self.body.append(f"{pad}try:")
            self.body.extend("    " + line for line in call)
            self.body.append(f"{pad}except Exception:  # fault path")
            self._walk(fault, indent + 1)
        else:
            self.body.extend(call)
        self._walk(self._next(el), indent)

    def _emit_decision(self, el: FlowElement, indent: int) -> None:
        pad = "    " * indent
        self.body.append(f"{pad}# Decision: {el.name}")
        if not el.rules:
            self._walk(self._connector_target(el, ConnectorKind.DEFAULT), indent)
            return
        for i, rule in enumerate(el.rules):
            keyword = "if" if i == 0 else "elif"
            self.body.append(f"{pad}{keyword} {self._rule_expr(rule)}:")
            target = rule.connector.target if rule.connector else None
            self._walk(target, indent + 1)
        # Default branch.
        self.body.append(f"{pad}else:")
        self._walk(self._connector_target(el, ConnectorKind.DEFAULT), indent + 1)

    def _emit_loop(self, el: FlowElement, indent: int) -> None:
        pad = "    " * indent
        coll = el.collection_reference or ""
        coll_expr = self._ref_expr(coll) if coll else "[]"
        self.body.append(f"{pad}# Loop: {el.name} over {coll!r}")
        self.body.append(f"{pad}for _item in ({coll_expr} or []):")
        self.body.append(f"{pad}    self.ctx[{el.name!r}] = _item")
        body_target = self._connector_target(el, ConnectorKind.LOOP_NEXT)
        if body_target:
            self._walk(body_target, indent + 1)
        else:
            self.body.append(f"{pad}    pass")
        # After the loop completes.
        self._walk(self._connector_target(el, ConnectorKind.LOOP_END), indent)

    def _emit_assignment(self, el: FlowElement, indent: int) -> None:
        pad = "    " * indent
        self.body.append(f"{pad}# Assignment: {el.name}")
        wrote = False
        for w in el.field_writes:
            if not w.field:
                continue
            target = self._assign_target(w.field)
            self.body.append(f"{pad}{target} = {self._value_expr(w.value, w.value_kind)}")
            wrote = True
        if not wrote:
            self.body.append(f"{pad}pass")
        self._walk(self._next(el), indent)

    def _emit_subflow(self, el: FlowElement, indent: int) -> None:
        pad = "    " * indent
        child = f"Flow_{_safe_id(el.flow_name)}" if el.flow_name else "UnknownSubflow"
        self.body.append(f"{pad}# Subflow → {el.flow_name!r}")
        self.body.append(f"{pad}self.ctx[{el.name!r}] = await workflow.execute_child_workflow(")
        self.body.append(f"{pad}    {child}.run,")
        self.body.append(f"{pad}    record,")
        self.body.append(f"{pad}    id=workflow.info().workflow_id + {':' + el.name!r},")
        self.body.append(f"{pad})")
        self._walk(self._next(el), indent)

    def _emit_pause(self, el: FlowElement, indent: int) -> None:
        pad = "    " * indent
        kind = el.element_type.value
        self.body.append(
            f"{pad}# {kind} {el.name!r} requires human/async input — "
            "implement as a Temporal signal/wait. Skeleton continues."
        )
        # WAIT elements branch on a default connector; screens just continue.
        nxt = self._connector_target(el, ConnectorKind.DEFAULT) or self._next(el)
        self._walk(nxt, indent)

    # -- expression helpers ------------------------------------------------

    def _rule_expr(self, rule: FlowDecisionRule) -> str:
        if not rule.conditions:
            return "True"
        joiner = _CONDITION_LOGIC.get(rule.condition_logic.lower(), " and ")
        parts = [
            self._cond_expr(c.left, c.operator, c.right, c.right_kind) for c in rule.conditions
        ]
        expr = joiner.join(parts)
        if rule.condition_logic.lower() not in _CONDITION_LOGIC and len(parts) > 1:
            expr += f"  # TODO: custom logic {rule.condition_logic!r}"
        return expr

    def _cond_expr(
        self, left: str, operator: str, right: str | None, right_kind: str | None
    ) -> str:
        lhs = self._ref_expr(left)
        rhs = self._value_expr(right, right_kind)
        if operator in _OP_TO_PY:
            return f"{lhs} {_OP_TO_PY[operator]} {rhs}"
        if operator in {"Contains", "Includes"}:
            return f"{rhs} in ({lhs} or '')"
        if operator == "StartsWith":
            return f"str({lhs} or '').startswith({rhs})"
        if operator in {"IsNull", "IsBlank"}:
            # right booleanValue true → "is null"
            negate = str(right).lower() == "true"
            return f"({lhs} is None)" if negate else f"({lhs} is not None)"
        # IsChanged / unsupported operators can't be evaluated statelessly.
        return f"True  # TODO: operator {operator!r} on {left!r}"

    def _ref_expr(self, ref: str) -> str:
        """Translate a Flow reference into a Python expression over record/ctx."""
        if not ref:
            return "None"
        if ref.startswith("$Record."):
            return f"record.get({ref.split('.', 1)[1]!r})"
        if ref == "$Record":
            return "record"
        base = ref.split(".", 1)[0]
        if base in self.resource_names or base in self.visited:
            # Variable, or output of a prior element stored in ctx.
            return f"self.ctx.get({base!r})"
        # Default: treat as a record field.
        field = ref.split(".", 1)[1] if "." in ref else ref
        return f"record.get({field!r})"

    def _value_expr(self, value: str | None, kind: str | None) -> str:
        if value is None:
            return "None"
        if kind == "numberValue":
            return value if _looks_numeric(value) else repr(value)
        if kind == "booleanValue":
            return "True" if str(value).lower() == "true" else "False"
        if kind in {"elementReference", "reference"}:
            return self._ref_expr(value)
        return repr(value)

    def _assign_target(self, field: str) -> str:
        if field.startswith("$Record."):
            return f"record[{field.split('.', 1)[1]!r}]"
        if "." in field:
            head, tail = field.split(".", 1)
            return f"self.ctx.setdefault({head!r}, {{}})[{tail!r}]"
        return f"self.ctx[{field!r}]"

    # -- connector helpers -------------------------------------------------

    def _entry_target(self) -> str | None:
        if self.ir.start and self.ir.start.connector:
            return self.ir.start.connector.target
        # Fall back to the first element if start has no immediate connector.
        return self.ir.elements[0].name if self.ir.elements else None

    def _next(self, el: FlowElement) -> str | None:
        return self._connector_target(el, ConnectorKind.NEXT)

    def _connector_target(self, el: FlowElement, kind: ConnectorKind) -> str | None:
        for conn in el.connectors:
            if conn.kind is kind:
                return conn.target
        return None

    def _register_activity(self, el: FlowElement) -> str:
        act = f"act_{_safe_id(el.name)}"
        if act not in self.activities:
            self.activities[act] = (el.element_type.value, self._activity_detail(el))
        return act

    def _activity_detail(self, el: FlowElement) -> str:
        """Human-readable activity description, resolving $Record DML targets."""
        if el.element_type in {
            FlowElementType.RECORD_CREATE,
            FlowElementType.RECORD_UPDATE,
            FlowElementType.RECORD_DELETE,
        }:
            obj = el.object
            if not obj and self.ir.start and self.ir.start.object:
                # record-update/delete against $Record → the trigger object.
                obj = self.ir.start.object
            op = el.element_type.value.replace("record_", "")
            fields = ", ".join(w.field for w in el.field_writes if w.field) or "—"
            return f"{op} {obj or '?'} (fields: {fields})"
        return _activity_detail(el)

    # -- assembly ----------------------------------------------------------

    def _assemble(self, sched_notes: list[str]) -> str:
        parts = [_HEADER, ""]
        for act, (etype, detail) in self.activities.items():
            parts.append(_activity_def(act, etype, detail, self.ir.api_name))
        parts.append("")
        parts.append("@workflow.defn")
        parts.append(f"class {self.cls}:")
        parts.append(
            f'    """Translated from Salesforce {self.ir.process_type} Flow: {self.ir.api_name}.'
        )
        parts.append("")
        parts.append(
            f"    Structurally generated from the Flow IR "
            f"({len(self.ir.elements)} elements, "
            f"{len(self.ir.control_flow_edges())} connectors). Activities are stubs."
        )
        parts.append('    """')
        parts.append("")
        parts.append("    @workflow.run")
        parts.append("    async def run(self, record: dict[str, Any]) -> dict[str, Any]:")
        parts.append("        self.ctx: dict[str, Any] = {}")
        parts.extend(sched_notes)
        parts.extend(self.body)
        parts.append("        return self.ctx")
        parts.append("")
        return "\n".join(parts)


def _activity_detail(el: FlowElement) -> str:
    if el.element_type in {
        FlowElementType.RECORD_CREATE,
        FlowElementType.RECORD_UPDATE,
        FlowElementType.RECORD_DELETE,
    }:
        op = el.element_type.value.replace("record_", "")
        fields = ", ".join(w.field for w in el.field_writes if w.field) or "—"
        return f"{op} {el.object or '?'} (fields: {fields})"
    if el.element_type is FlowElementType.RECORD_LOOKUP:
        return f"query {el.object or '?'} (fields: {', '.join(el.queried_fields) or '—'})"
    if el.element_type is FlowElementType.ACTION_CALL:
        return f"action {el.action_type or '?'}:{el.action_name or '?'}"
    if el.element_type is FlowElementType.APEX_PLUGIN_CALL:
        return f"apex {el.apex_class or '?'}"
    return el.element_type.value


def _activity_def(act: str, etype: str, detail: str, flow_api_name: str) -> str:
    return (
        "@activity.defn\n"
        f"async def {act}(record: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]:\n"
        f'    """{etype}: {detail}."""\n'
        f'    activity.logger.info("{act}", extra={{"flow": {flow_api_name!r}}})\n'
        f"    # TODO: implement via the MCP gateway — {detail}\n"
        "    return {}\n"
    )


def _looks_numeric(v: str) -> bool:
    try:
        float(v)
        return True
    except ValueError:
        return False
