"""Tier 2 translator — Component → Temporal workflow code.

Handles approval processes, schedule-triggered flows, and after-save flows
with callouts. Emits Python source that runs against ``temporalio.workflow``
+ ``temporalio.activity``. The generated code is **runnable** — `python -c
"import emitted_module"` succeeds; deploying to a real Temporal worker is a
separate operational step (Phase 5).
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from offramp.core.models import CategoryName, Component


@dataclass(frozen=True)
class GeneratedWorkflow:
    """One emitted Temporal workflow + its activity definitions."""

    workflow_id: str
    workflow_name: str  # Python class name
    activity_names: tuple[str, ...]
    code: str


def _safe_id(s: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"w_{cleaned}"
    return cleaned


_HEADER = '''\
"""Auto-generated Temporal workflow.

Generated by offramp.generate.tier2. Do not edit by hand — regenerate.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import activity, workflow
'''


def translate(component: Component) -> GeneratedWorkflow:
    """Dispatch by category and emit a runnable Temporal module."""
    if component.category is CategoryName.APPROVAL_PROCESS:
        return _translate_approval(component)
    if component.category is CategoryName.SCHEDULE_TRIGGERED_FLOW:
        return _translate_scheduled(component)
    if component.category in {
        CategoryName.AUTO_RESPONSE_RULE,
        CategoryName.ESCALATION_RULE,
        CategoryName.PLATFORM_EVENT,
        CategoryName.PLATFORM_EVENT_TRIGGERED_FLOW,
        CategoryName.FLOW_ORCHESTRATION,
        CategoryName.CHANGE_DATA_CAPTURE,
        CategoryName.APEX_CLASS,
    }:
        return _translate_generic_workflow(component)
    raise NotImplementedError(f"Tier 2 translator does not yet handle {component.category.value}")


def _translate_approval(component: Component) -> GeneratedWorkflow:
    name = _safe_id(component.api_name or component.name)
    cls = f"Approval_{name}"
    code = (
        _HEADER
        + f"""

@activity.defn
async def submit_for_approval(record_id: str) -> str:
    \"\"\"Open the approval; return the approval-instance id.\"\"\"
    activity.logger.info("submit_for_approval", extra={{"record_id": record_id}})
    return f"apr_{{record_id}}"


@activity.defn
async def wait_for_approver_decision(approval_instance_id: str) -> str:
    \"\"\"Poll/listen for the approver's decision.\"\"\"
    activity.logger.info("wait_for_approver_decision", extra={{"approval": approval_instance_id}})
    # In production this awaits a Platform Event signal; for the generated
    # skeleton we surface a placeholder string.
    return "approved"


@activity.defn
async def apply_final_actions(record_id: str, decision: str) -> dict[str, Any]:
    activity.logger.info("apply_final_actions", extra={{"record_id": record_id, "decision": decision}})
    return {{"record_id": record_id, "decision": decision}}


@workflow.defn
class {cls}:
    \"\"\"Translated from Salesforce Approval Process: {component.name}.\"\"\"

    @workflow.run
    async def run(self, record_id: str) -> dict[str, Any]:
        approval_id = await workflow.execute_activity(
            submit_for_approval,
            record_id,
            start_to_close_timeout=timedelta(minutes=5),
        )
        decision = await workflow.execute_activity(
            wait_for_approver_decision,
            approval_id,
            start_to_close_timeout=timedelta(days=14),
        )
        return await workflow.execute_activity(
            apply_final_actions,
            args=[record_id, decision],
            start_to_close_timeout=timedelta(minutes=5),
        )
"""
    )
    return GeneratedWorkflow(
        workflow_id=f"approval.{component.name}",
        workflow_name=cls,
        activity_names=(
            "submit_for_approval",
            "wait_for_approver_decision",
            "apply_final_actions",
        ),
        code=code,
    )


def _translate_scheduled(component: Component) -> GeneratedWorkflow:
    name = _safe_id(component.api_name or component.name)
    cls = f"Scheduled_{name}"
    code = (
        _HEADER
        + f"""

@activity.defn
async def execute_scheduled_step(payload: dict[str, Any]) -> dict[str, Any]:
    activity.logger.info("execute_scheduled_step")
    return payload


@workflow.defn
class {cls}:
    \"\"\"Translated from Salesforce Schedule-Triggered Flow: {component.name}.

    Schedule itself is configured at deployment time via Temporal's
    ``ScheduleClient`` — the workflow body just executes the per-tick logic.
    \"\"\"

    @workflow.run
    async def run(self, payload: dict[str, Any]) -> dict[str, Any]:
        return await workflow.execute_activity(
            execute_scheduled_step,
            payload,
            start_to_close_timeout=timedelta(minutes=15),
        )
"""
    )
    return GeneratedWorkflow(
        workflow_id=f"scheduled.{component.name}",
        workflow_name=cls,
        activity_names=("execute_scheduled_step",),
        code=code,
    )


def _translate_generic_workflow(component: Component) -> GeneratedWorkflow:
    name = _safe_id(component.api_name or component.name)
    cls = f"Wf_{name}"
    code = (
        _HEADER
        + f"""

@activity.defn
async def perform_step(payload: dict[str, Any]) -> dict[str, Any]:
    activity.logger.info("perform_step", extra={{"category": "{component.category.value}"}})
    return payload


@workflow.defn
class {cls}:
    \"\"\"Translated from Salesforce {component.category.value}: {component.name}.\"\"\"

    @workflow.run
    async def run(self, payload: dict[str, Any]) -> dict[str, Any]:
        return await workflow.execute_activity(
            perform_step,
            payload,
            start_to_close_timeout=timedelta(minutes=10),
        )
"""
    )
    return GeneratedWorkflow(
        workflow_id=f"{component.category.value}.{component.name}",
        workflow_name=cls,
        activity_names=("perform_step",),
        code=code,
    )
