"""Tier 3 translator — Component → LangGraph StateGraph code.

Targets components requiring interpretation of unstructured input or
context-dependent decisions: Screen Flows, business-logic-heavy LWCs,
or Flows with too many decision nodes for a deterministic translation.

LangGraph runs INSIDE Temporal activities (architecture §5.3) so the
generated module exposes both:
* a ``build_graph()`` factory returning a compiled LangGraph
* an ``activity`` decorator wrapping it for Temporal composition
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from offramp.core.models import Component


@dataclass(frozen=True)
class GeneratedAgent:
    """One emitted LangGraph agent."""

    agent_id: str
    builder_name: str  # Python factory function name
    code: str


def _safe_id(s: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"a_{cleaned}"
    return cleaned


_HEADER = '''\
"""Auto-generated LangGraph agent.

Generated by offramp.generate.tier3. Do not edit by hand — regenerate.

Runs inside a Temporal activity for durability — see architecture §5.3.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any
'''


def translate(component: Component) -> GeneratedAgent:
    name = _safe_id(component.api_name or component.name)
    builder = f"build_{name}"
    code = (
        _HEADER
        + f"""


@dataclass
class {name}State:
    \"\"\"Mutable state passed between graph nodes.\"\"\"

    input: dict[str, Any]
    classification: str | None = None
    output: dict[str, Any] | None = None


def _classify(state: {name}State) -> {name}State:
    \"\"\"Placeholder classifier — replace with real LLM call at deploy time.\"\"\"
    txt = str(state.input.get("text") or "")
    state.classification = "high_priority" if "urgent" in txt.lower() else "normal"
    return state


def _route(state: {name}State) -> str:
    return state.classification or "normal"


def _handle_high(state: {name}State) -> {name}State:
    state.output = {{"action": "escalate", "input": state.input}}
    return state


def _handle_normal(state: {name}State) -> {name}State:
    state.output = {{"action": "queue", "input": state.input}}
    return state


def {builder}():
    \"\"\"Build a compiled LangGraph for component {component.name}.

    Returns ``Any`` to avoid a hard import dependency on langgraph at
    package-load time; importers should ``from langgraph.graph import
    StateGraph, END`` themselves and pass the constructed graph through.
    \"\"\"
    try:
        from langgraph.graph import END, StateGraph
    except ImportError as exc:  # pragma: no cover — surfaced at import time
        raise RuntimeError(
            "langgraph is not installed; add it to the runtime extras before deploying this agent"
        ) from exc

    graph = StateGraph({name}State)
    graph.add_node("classify", _classify)
    graph.add_node("handle_high", _handle_high)
    graph.add_node("handle_normal", _handle_normal)
    graph.set_entry_point("classify")
    graph.add_conditional_edges(
        "classify",
        _route,
        {{"high_priority": "handle_high", "normal": "handle_normal"}},
    )
    graph.add_edge("handle_high", END)
    graph.add_edge("handle_normal", END)
    return graph.compile()
"""
    )
    return GeneratedAgent(
        agent_id=f"langgraph.{component.name}",
        builder_name=builder,
        code=code,
    )
