"""Emit MCP tool definitions for auto-adaptable managed-package dependencies.

Each generated tool wraps a callable that delegates to the package's REST
endpoint via the MCP gateway. Phase 3 emits the tool definitions; the
runtime wiring happens in Phase 5 when the gateway exposes the MCP server
publicly.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from offramp.generate.adapters.detector import PackageDependency


@dataclass(frozen=True)
class GeneratedAdapter:
    """One emitted adapter module (auto OR hand-tuned reference)."""

    package_name: str
    namespace: str
    module_name: str
    code: str


_HEADER = '''\
"""Auto-generated managed-package adapter.

Generated by offramp.generate.adapters.mcp_emitter — do not edit by hand.
"""
from __future__ import annotations

from typing import Any
'''


def _safe_id(s: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"a_{cleaned}"
    return cleaned


def emit(dep: PackageDependency) -> GeneratedAdapter:
    """Auto-emit a generic adapter for a managed-package namespace."""
    safe_pkg = _safe_id(dep.package_name)
    components_doc = ", ".join(dep.contributing_components[:5])
    if len(dep.contributing_components) > 5:
        components_doc += f", ... ({len(dep.contributing_components)} total)"
    code = (
        _HEADER
        + f'''

# Adapter for the "{dep.package_name}" managed package (namespace "{dep.namespace}").
# Contributing components: {components_doc}

PACKAGE_NAME = {dep.package_name!r}
NAMESPACE = {dep.namespace!r}


def call(method: str, args: dict[str, Any]) -> Any:
    """Generic call into the managed package via the MCP gateway.

    Real implementation routes through the MCP gateway's adapter channel,
    which handles auth + quota allocation. Phase 5 wires this to the live
    Salesforce REST surface.
    """
    raise NotImplementedError(
        "Adapter call() requires a live MCP gateway. Implementation lands in Phase 5."
    )
'''
    )
    return GeneratedAdapter(
        package_name=dep.package_name,
        namespace=dep.namespace,
        module_name=f"adapter_{safe_pkg}",
        code=code,
    )
