# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "pubsub_api.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10pubsub_api.proto\x12\x0b\x65ventbus.v1"\x94\x01\n\x0c\x46\x65tchRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x30\n\rreplay_preset\x18\x02 \x01(\x0e\x32\x19.eventbus.v1.ReplayPreset\x12\x11\n\treplay_id\x18\x03 \x01(\x0c\x12\x15\n\rnum_requested\x18\x04 \x01(\x05\x12\x14\n\x0c\x61uth_refresh\x18\x05 \x01(\t"\x84\x01\n\rFetchResponse\x12*\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1a.eventbus.v1.ConsumerEvent\x12\x18\n\x10latest_replay_id\x18\x02 \x01(\x0c\x12\x0e\n\x06rpc_id\x18\x03 \x01(\t\x12\x1d\n\x15pending_num_requested\x18\x04 \x01(\x05"M\n\rConsumerEvent\x12)\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x1a.eventbus.v1.ProducerEvent\x12\x11\n\treplay_id\x18\x02 \x01(\x0c"\xa9\x01\n\rProducerEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tschema_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x38\n\x07headers\x18\x04 \x03(\x0b\x32\'.eventbus.v1.ProducerEvent.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01""\n\rSchemaRequest\x12\x11\n\tschema_id\x18\x01 \x01(\t"4\n\nSchemaInfo\x12\x11\n\tschema_id\x18\x01 \x01(\t\x12\x13\n\x0bschema_json\x18\x02 \x01(\t""\n\x0cTopicRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t"\x83\x01\n\tTopicInfo\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x13\n\x0btenant_guid\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61n_publish\x18\x03 \x01(\x08\x12\x15\n\rcan_subscribe\x18\x04 \x01(\x08\x12\x11\n\tschema_id\x18\x05 \x01(\t\x12\x0e\n\x06rpc_id\x18\x06 \x01(\x05*4\n\x0cReplayPreset\x12\n\n\x06LATEST\x10\x00\x12\x0c\n\x08\x45\x41RLIEST\x10\x01\x12\n\n\x06\x43USTOM\x10\x02\x32\xd1\x01\n\x06PubSub\x12\x46\n\tSubscribe\x12\x19.eventbus.v1.FetchRequest\x1a\x1a.eventbus.v1.FetchResponse(\x01\x30\x01\x12@\n\tGetSchema\x12\x1a.eventbus.v1.SchemaRequest\x1a\x17.eventbus.v1.SchemaInfo\x12=\n\x08GetTopic\x12\x19.eventbus.v1.TopicRequest\x1a\x16.eventbus.v1.TopicInfob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pubsub_api_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PRODUCEREVENT_HEADERSENTRY"]._loaded_options = None
    _globals["_PRODUCEREVENT_HEADERSENTRY"]._serialized_options = b"8\001"
    _globals["_REPLAYPRESET"]._serialized_start = 830
    _globals["_REPLAYPRESET"]._serialized_end = 882
    _globals["_FETCHREQUEST"]._serialized_start = 34
    _globals["_FETCHREQUEST"]._serialized_end = 182
    _globals["_FETCHRESPONSE"]._serialized_start = 185
    _globals["_FETCHRESPONSE"]._serialized_end = 317
    _globals["_CONSUMEREVENT"]._serialized_start = 319
    _globals["_CONSUMEREVENT"]._serialized_end = 396
    _globals["_PRODUCEREVENT"]._serialized_start = 399
    _globals["_PRODUCEREVENT"]._serialized_end = 568
    _globals["_PRODUCEREVENT_HEADERSENTRY"]._serialized_start = 522
    _globals["_PRODUCEREVENT_HEADERSENTRY"]._serialized_end = 568
    _globals["_SCHEMAREQUEST"]._serialized_start = 570
    _globals["_SCHEMAREQUEST"]._serialized_end = 604
    _globals["_SCHEMAINFO"]._serialized_start = 606
    _globals["_SCHEMAINFO"]._serialized_end = 658
    _globals["_TOPICREQUEST"]._serialized_start = 660
    _globals["_TOPICREQUEST"]._serialized_end = 694
    _globals["_TOPICINFO"]._serialized_start = 697
    _globals["_TOPICINFO"]._serialized_end = 828
    _globals["_PUBSUB"]._serialized_start = 885
    _globals["_PUBSUB"]._serialized_end = 1094
# @@protoc_insertion_point(module_scope)
