# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""


import grpc
import pubsub_api_pb2 as pubsub__api__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in pubsub_api_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PubSubStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.stream_stream(
            "/eventbus.v1.PubSub/Subscribe",
            request_serializer=pubsub__api__pb2.FetchRequest.SerializeToString,
            response_deserializer=pubsub__api__pb2.FetchResponse.FromString,
            _registered_method=True,
        )
        self.GetSchema = channel.unary_unary(
            "/eventbus.v1.PubSub/GetSchema",
            request_serializer=pubsub__api__pb2.SchemaRequest.SerializeToString,
            response_deserializer=pubsub__api__pb2.SchemaInfo.FromString,
            _registered_method=True,
        )
        self.GetTopic = channel.unary_unary(
            "/eventbus.v1.PubSub/GetTopic",
            request_serializer=pubsub__api__pb2.TopicRequest.SerializeToString,
            response_deserializer=pubsub__api__pb2.TopicInfo.FromString,
            _registered_method=True,
        )


class PubSubServicer:
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request_iterator, context):
        """Bidirectional streaming subscribe — server pushes events as they're
        available; client periodically sends FetchRequest to request more.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSchema(self, request, context):
        """Cached schema fetch — Avro schema for a given event topic version."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTopic(self, request, context):
        """Topic metadata."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PubSubServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Subscribe": grpc.stream_stream_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=pubsub__api__pb2.FetchRequest.FromString,
            response_serializer=pubsub__api__pb2.FetchResponse.SerializeToString,
        ),
        "GetSchema": grpc.unary_unary_rpc_method_handler(
            servicer.GetSchema,
            request_deserializer=pubsub__api__pb2.SchemaRequest.FromString,
            response_serializer=pubsub__api__pb2.SchemaInfo.SerializeToString,
        ),
        "GetTopic": grpc.unary_unary_rpc_method_handler(
            servicer.GetTopic,
            request_deserializer=pubsub__api__pb2.TopicRequest.FromString,
            response_serializer=pubsub__api__pb2.TopicInfo.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "eventbus.v1.PubSub", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("eventbus.v1.PubSub", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PubSub:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/eventbus.v1.PubSub/Subscribe",
            pubsub__api__pb2.FetchRequest.SerializeToString,
            pubsub__api__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventbus.v1.PubSub/GetSchema",
            pubsub__api__pb2.SchemaRequest.SerializeToString,
            pubsub__api__pb2.SchemaInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTopic(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventbus.v1.PubSub/GetTopic",
            pubsub__api__pb2.TopicRequest.SerializeToString,
            pubsub__api__pb2.TopicInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
