"""``offramp recipes``: generate verify recipes from the schema and the process model."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from offramp.cli.health import load_extract
from offramp.verify.recipes import generate_recipes


def add_recipes_subparser(sub: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    p = sub.add_parser(
        "recipes",
        help="Generate `offramp verify` recipes for every verifiable flow (review, then run).",
    )
    p.add_argument("--from", dest="extract_dir", type=Path, required=True, help="Extract dir.")
    p.add_argument("--flow", action="append", default=[], help="Flow API name (repeatable).")
    p.add_argument(
        "--recipes", type=Path, help="Existing hand-written recipes to keep (they win unchanged)."
    )
    p.add_argument("--out", type=Path, help="Write the merged recipes here (else print).")
    p.set_defaults(func=_run)


def _run(args: argparse.Namespace) -> int:
    _, defs, schema = load_extract(args.extract_dir)
    existing = json.loads(args.recipes.read_text(encoding="utf-8")) if args.recipes else {}
    existing = {k: v for k, v in existing.items() if not k.startswith("_")}
    recipes = generate_recipes(defs, schema, existing=existing, only=args.flow or None)
    doc = {
        "_comment": (
            "Generated by `offramp recipes`; entries with _generated were synthesised from the "
            "schema and entry conditions, _needs lists what a person must decide. Run with "
            "`offramp verify --org <alias> --from <extract> --recipes <this file>`."
        ),
        **recipes,
    }
    text = json.dumps(doc, indent=2)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text + "\n", encoding="utf-8")
        needs = sum(1 for r in recipes.values() if r.get("_needs"))
        print(f"wrote {len(recipes)} recipes to {args.out} ({needs} need a decision)")
    else:
        print(text)
    return 0
